//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServicesMechanic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TheService()
        {
            this.ServiceList = new HashSet<ServiceList>();
        }
    
        public int IdTheService { get; set; }
        public string NameTheService { get; set; }
        public string DescriptionTheService { get; set; }
        public byte[] PreviewImageTheService { get; set; }
        public int IdServiceType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceList> ServiceList { get; set; }
        public virtual ServiceType ServiceType { get; set; }
    }
}
