//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mechanic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int IdService { get; set; }
        public Nullable<System.DateTime> CreatedDateService { get; set; }
        public int DeletCodeService { get; set; }
        public string MechanicCommentService { get; set; }
        public string ClientCommentService { get; set; }
        public Nullable<int> MechanicCalificationService { get; set; }
        public Nullable<int> ClientCalificationService { get; set; }
        public int IdClient { get; set; }
        public int IdServiceList { get; set; }
        public int IdStatusService { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual ServiceList ServiceList { get; set; }
        public virtual StatusService StatusService { get; set; }
    }
}
